# Generated by Django 5.1.6 on 2025-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='story',
            field=models.CharField(default='BUG', max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='NEW', max_length=20),
        ),
    ]
