# Generated by Django 5.1.6 on 2025-03-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_issue_options_issue_description_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.issue'),
        ),
    ]
