# Generated by Django 4.1 on 2023-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
