# Generated by Django 5.1.2 on 2024-11-23 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('projects', '0003_jiraproject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.jiraproject'),
        ),
    ]
