# Generated by Django 5.1.2 on 2024-11-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_registeruser_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='project_id',
        ),
    ]
