# Generated by Django 4.1 on 2023-04-01 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_topic_room_host_msssage_room_topic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Msssage",
            new_name="Message",
        ),
    ]
