# Generated by Django 4.1 on 2023-06-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_product_cart_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product_id",
            new_name="product",
        ),
    ]
