# Generated by Django 5.1.2 on 2024-10-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jiraissue',
            options={'ordering': ['-date_updated']},
        ),
    ]
