# Generated by Django 5.1.2 on 2024-11-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_alter_jiraissue_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
