# Generated by Django 5.1.2 on 2024-11-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_delete_registeruser'),
        ('projects', '0003_jiraproject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.jiraproject'),
        ),
    ]
