# Generated by Django 5.1.2 on 2024-11-27 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_jiraissue_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reported_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
