# Generated by Django 5.1.2 on 2024-11-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_jiraissue_reported_by_alter_jiraissue_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiraissue',
            old_name='name',
            new_name='summary',
        ),
    ]
