# Generated by Django 5.1.2 on 2024-11-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JiraProjects',
            new_name='JiraProject',
        ),
    ]
