# Generated by Django 5.1.2 on 2024-11-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_jiraprojects_jiraproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraproject',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
