# Generated by Django 4.1 on 2023-05-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory_quantity"),
        ("products", "0006_alter_product_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="brand_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="category_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
