# Generated by Django 4.1 on 2023-05-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory_quantity"),
        ("products", "0007_brand_brand_quantity_product_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="inventory_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventory",
            ),
        ),
    ]
