# Generated by Django 4.1 on 2023-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="address",
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
