# Generated by Django 4.1 on 2023-05-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_myuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
