# Generated by Django 4.1 on 2023-05-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_myuser_password1_myuser_password2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="password2",
        ),
    ]
